version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: /var/www/html/install_nginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /var/www/html/start_nginx.sh
      timeout: 300
      runas: root
